// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/side_nav/Admin.vue')['default']
    AsideList: typeof import('./src/components/side_nav/AsideList.vue')['default']
    AsideNav: typeof import('./src/components/side_nav/AsideNav.vue')['default']
    AsideOpenalMenu: typeof import('./src/components/side_nav/AsideOpenalMenu.vue')['default']
    AsideStaticMenu: typeof import('./src/components/side_nav/AsideStaticMenu.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HeaderNav: typeof import('./src/components/header_nav/HeaderNav.vue')['default']
    IndexContent: typeof import('./src/components/main_content/indexContent.vue')['default']
    LoginBox: typeof import('./src/components/login/LoginBox.vue')['default']
    ProfileInfo: typeof import('./src/components/main_content/profile/ProfileInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreManager: typeof import('./src/components/main_content/student/scoreManager.vue')['default']
    Student: typeof import('./src/components/side_nav/Student.vue')['default']
    Teacher: typeof import('./src/components/side_nav/Teacher.vue')['default']
    UpdatePsd: typeof import('./src/components/main_content/profile/UpdatePsd.vue')['default']
    UserInfo: typeof import('./src/components/header_nav/UserInfo.vue')['default']
  }
}
