// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideList: typeof import('./src/components/side_nav/AsideList.vue')['default']
    AsideOpenalMenu: typeof import('./src/components/side_nav/AsideOpenalMenu.vue')['default']
    AsideStaticMenu: typeof import('./src/components/side_nav/AsideStaticMenu.vue')['default']
    CourseManage: typeof import('./src/components/main_content/teacher/CourseManage.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HeaderNav: typeof import('./src/components/header_nav/HeaderNav.vue')['default']
    HomeContent: typeof import('./src/components/main_content/home/HomeContent.vue')['default']
    IndexContent: typeof import('./src/components/main_content/IndexContent.vue')['default']
    LoginBox: typeof import('./src/components/login/LoginBox.vue')['default']
    ProfileInfo: typeof import('./src/components/main_content/profile/ProfileInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreManager: typeof import('./src/components/main_content/student/ScoreManager.vue')['default']
    StudentManage: typeof import('./src/components/main_content/admin/StudentManage.vue')['default']
    StuProfile: typeof import('./src/components/main_content/student/StuProfile.vue')['default']
    TabBox: typeof import('./src/components/main_content/TabBox.vue')['default']
    TableBox: typeof import('./src/components/common/TableBox.vue')['default']
    TeaProfile: typeof import('./src/components/main_content/teacher/TeaProfile.vue')['default']
    TeaUpdatePwd: typeof import('./src/components/main_content/teacher/TeaUpdatePwd.vue')['default']
    UpdatePsd: typeof import('./src/components/main_content/profile/UpdatePsd.vue')['default']
    UpdatePwd: typeof import('./src/components/main_content/student/UpdatePwd.vue')['default']
    UserInfo: typeof import('./src/components/header_nav/UserInfo.vue')['default']
  }
}
